// productos.js
// Catálogo de Sonido Vivo, siguiendo el modelo de datos del Módulo 3 y 5 de la guía



const productos = [
    {
        "id": 1,
        "codigo": "GA001",
        "nombre": "Guitarra Acústica Folk",
        "marca": "Yamaha",
        "modelo": "F310",
        "categoria": "Guitarras Acústicas",
        "precio": 129990,
        "stock": 8,
        "descripcion": "Tapa de abeto, aros y fondo de meranti. Ideal para iniciantes.",
        "imagen": "https://placehold.co/600x400?text=Guitarras+Acústicas"
    },
    {
        "id": 2,
        "codigo": "GA002",
        "nombre": "Guitarra Acústica Dreadnought",
        "marca": "Fender",
        "modelo": "CD-60S",
        "categoria": "Guitarras Acústicas",
        "precio": 189990,
        "stock": 5,
        "descripcion": "Tapa de abeto macizo, brazo de caoba. Sonido cálido y proyectado.",
        "imagen": "https://placehold.co/600x400?text=Guitarras+Acústicas"
    },
    {
        "id": 3,
        "codigo": "GA003",
        "nombre": "Guitarra Acústica Clásica 4/4",
        "marca": "Yamaha",
        "modelo": "C40",
        "categoria": "Guitarras Acústicas",
        "precio": 89990,
        "stock": 10,
        "descripcion": "Nailon, tapa de abeto. Ideal para estudio y flamenco.",
        "imagen": "https://placehold.co/600x400?text=Guitarras+Acústicas"
    },
    {
        "id": 4,
        "codigo": "GA004",
        "nombre": "Guitarra Electroacústica",
        "marca": "Takamine",
        "modelo": "GN20CE",
        "categoria": "Guitarras Acústicas",
        "precio": 349990,
        "stock": 3,
        "descripcion": "Pickup integrado, afinador incorporado.",
        "imagen": "https://placehold.co/600x400?text=Guitarras+Acústicas"
    },
    {
        "id": 5,
        "codigo": "GA005",
        "nombre": "Guitarra 3/4 Niños",
        "marca": "Yamaha",
        "modelo": "JR1",
        "categoria": "Guitarras Acústicas",
        "precio": 79990,
        "stock": 6,
        "descripcion": "Tamaño reducido para niños de 6 a 10 años.",
        "imagen": "https://placehold.co/600x400?text=Guitarras+Acústicas"
    },
    {
        "id": 6,
        "codigo": "GE001",
        "nombre": "Guitarra Eléctrica Stratocaster",
        "marca": "Squier",
        "modelo": "Affinity Strat",
        "categoria": "Guitarras Eléctricas",
        "precio": 249990,
        "stock": 5,
        "descripcion": "Cuerpo de álamo, mástil de arce, pastillas SSS.",
        "imagen": "https://placehold.co/600x400?text=Guitarras+Eléctricas"
    },
    {
        "id": 7,
        "codigo": "GE002",
        "nombre": "Guitarra Eléctrica Les Paul",
        "marca": "Epiphone",
        "modelo": "Les Paul Std",
        "categoria": "Guitarras Eléctricas",
        "precio": 329990,
        "stock": 4,
        "descripcion": "Cuerpo caoba, tapa arce, pastillas humbucker.",
        "imagen": "https://placehold.co/600x400?text=Guitarras+Eléctricas"
    },
    {
        "id": 8,
        "codigo": "GE003",
        "nombre": "Guitarra Eléctrica SG",
        "marca": "Epiphone",
        "modelo": "SG Standard",
        "categoria": "Guitarras Eléctricas",
        "precio": 319990,
        "stock": 3,
        "descripcion": "Cuerpo caoba, mástil caoba, 2 humbuckers.",
        "imagen": "https://placehold.co/600x400?text=Guitarras+Eléctricas"
    },
    {
        "id": 9,
        "codigo": "GE004",
        "nombre": "Guitarra Eléctrica Telecaster",
        "marca": "Squier",
        "modelo": "Affinity Tele",
        "categoria": "Guitarras Eléctricas",
        "precio": 239990,
        "stock": 4,
        "descripcion": "Cuerpo álamo, clavijero vintage, 2 pastillas single.",
        "imagen": "https://placehold.co/600x400?text=Guitarras+Eléctricas"
    },
    {
        "id": 10,
        "codigo": "GE005",
        "nombre": "Guitarra Eléctrica Semi-hollow",
        "marca": "Epiphone",
        "modelo": "ES-335",
        "categoria": "Guitarras Eléctricas",
        "precio": 549990,
        "stock": 2,
        "descripcion": "Semi-hueca, 2 humbuckers, ideal para jazz y blues.",
        "imagen": "https://placehold.co/600x400?text=Guitarras+Eléctricas"
    },
    {
        "id": 11,
        "codigo": "BA001",
        "nombre": "Bajo Eléctrico 4 Cuerdas",
        "marca": "Squier",
        "modelo": "Affinity PJ",
        "categoria": "Bajos Eléctricos",
        "precio": 299990,
        "stock": 5,
        "descripcion": "Pickup PJ, cuerpo álamo, mástil arce.",
        "imagen": "https://placehold.co/600x400?text=Bajos+Eléctricos"
    },
    {
        "id": 12,
        "codigo": "BA002",
        "nombre": "Bajo Eléctrico Jazz Bass",
        "marca": "Fender",
        "modelo": "Player Jazz",
        "categoria": "Bajos Eléctricos",
        "precio": 699990,
        "stock": 2,
        "descripcion": "Alder body, 2 Alnico V Jazz single-coil.",
        "imagen": "https://placehold.co/600x400?text=Bajos+Eléctricos"
    },
    {
        "id": 13,
        "codigo": "BA003",
        "nombre": "Bajo Acústico 4 Cuerdas",
        "marca": "Yamaha",
        "modelo": "APX700II",
        "categoria": "Bajos Eléctricos",
        "precio": 429990,
        "stock": 2,
        "descripcion": "Electroacústico, afinador incorporado.",
        "imagen": "https://placehold.co/600x400?text=Bajos+Eléctricos"
    },
    {
        "id": 14,
        "codigo": "BT001",
        "nombre": "Batería Acústica 5 piezas",
        "marca": "Pearl",
        "modelo": "Roadshow",
        "categoria": "Baterías",
        "precio": 599990,
        "stock": 2,
        "descripcion": "Incluye stands, platillos y pedal de bombo.",
        "imagen": "https://placehold.co/600x400?text=Baterías"
    },
    {
        "id": 15,
        "codigo": "BT002",
        "nombre": "Batería Electrónica 8 pads",
        "marca": "Roland",
        "modelo": "TD-02KV",
        "categoria": "Baterías",
        "precio": 799990,
        "stock": 2,
        "descripcion": "Módulo TD-02, 8 pads de goma, pedal hi-hat.",
        "imagen": "https://placehold.co/600x400?text=Baterías"
    },
    {
        "id": 16,
        "codigo": "BT003",
        "nombre": "Caja Snare 14\"",
        "marca": "Pearl",
        "modelo": "STE1450",
        "categoria": "Baterías",
        "precio": 89990,
        "stock": 4,
        "descripcion": "Acero, 14x5\", 10 tensores.",
        "imagen": "https://placehold.co/600x400?text=Baterías"
    },
    {
        "id": 17,
        "codigo": "BT004",
        "nombre": "Platillo Hi-Hat 14\"",
        "marca": "Zildjian",
        "modelo": "A Series",
        "categoria": "Baterías",
        "precio": 149990,
        "stock": 3,
        "descripcion": "Latón B20, sonido brillante y claro.",
        "imagen": "https://placehold.co/600x400?text=Baterías"
    },
    {
        "id": 18,
        "codigo": "BT005",
        "nombre": "Platillo Crash 16\"",
        "marca": "Zildjian",
        "modelo": "A Series",
        "categoria": "Baterías",
        "precio": 129990,
        "stock": 3,
        "descripcion": "Latón B20, ataque rápido.",
        "imagen": "https://placehold.co/600x400?text=Baterías"
    },
    {
        "id": 19,
        "codigo": "TC001",
        "nombre": "Teclado Digital 61 teclas",
        "marca": "Yamaha",
        "modelo": "PSR-E373",
        "categoria": "Teclados y Pianos",
        "precio": 249990,
        "stock": 4,
        "descripcion": "61 teclas sensibles al tacto, 622 voces.",
        "imagen": "https://placehold.co/600x400?text=Teclados+y+Pianos"
    },
    {
        "id": 20,
        "codigo": "TC002",
        "nombre": "Piano Digital 88 teclas",
        "marca": "Yamaha",
        "modelo": "P-45",
        "categoria": "Teclados y Pianos",
        "precio": 499990,
        "stock": 2,
        "descripcion": "88 teclas pesadas, 10 voces, pedal sustain incluido.",
        "imagen": "https://placehold.co/600x400?text=Teclados+y+Pianos"
    },
    {
        "id": 21,
        "codigo": "TC003",
        "nombre": "Sintetizador 49 teclas",
        "marca": "Arturia",
        "modelo": "MiniLab MKII",
        "categoria": "Teclados y Pianos",
        "precio": 129990,
        "stock": 5,
        "descripcion": "MIDI controller, 49 mini teclas.",
        "imagen": "https://placehold.co/600x400?text=Teclados+y+Pianos"
    },
    {
        "id": 22,
        "codigo": "TC004",
        "nombre": "Teclado MIDI 88 teclas",
        "marca": "M-Audio",
        "modelo": "Hammer 88",
        "categoria": "Teclados y Pianos",
        "precio": 399990,
        "stock": 2,
        "descripcion": "88 teclas martillo, sin sonidos propios.",
        "imagen": "https://placehold.co/600x400?text=Teclados+y+Pianos"
    },
    {
        "id": 23,
        "codigo": "AM001",
        "nombre": "Amplificador Guitarra 15W",
        "marca": "Fender",
        "modelo": "Frontman 15G",
        "categoria": "Amplificadores",
        "precio": 99990,
        "stock": 5,
        "descripcion": "15W, distorsión incorporada, entrada auxiliar.",
        "imagen": "https://placehold.co/600x400?text=Amplificadores"
    },
    {
        "id": 24,
        "codigo": "AM002",
        "nombre": "Amplificador Guitarra 40W",
        "marca": "Marshall",
        "modelo": "MG40GFX",
        "categoria": "Amplificadores",
        "precio": 299990,
        "stock": 3,
        "descripcion": "40W, 4 canales, efectos digitales integrados.",
        "imagen": "https://placehold.co/600x400?text=Amplificadores"
    },
    {
        "id": 25,
        "codigo": "AM003",
        "nombre": "Amplificador Bajo 100W",
        "marca": "Hartke",
        "modelo": "HD100",
        "categoria": "Amplificadores",
        "precio": 449990,
        "stock": 2,
        "descripcion": "100W, tweeter integrado, ecualizador de 4 bandas.",
        "imagen": "https://placehold.co/600x400?text=Amplificadores"
    },
    {
        "id": 26,
        "codigo": "AM004",
        "nombre": "Amplificador Acústico 40W",
        "marca": "Fishman",
        "modelo": "Loudbox Mini",
        "categoria": "Amplificadores",
        "precio": 499990,
        "stock": 2,
        "descripcion": "60W, 2 canales, reverb y chorus incorporados.",
        "imagen": "https://placehold.co/600x400?text=Amplificadores"
    },
    {
        "id": 27,
        "codigo": "MI001",
        "nombre": "Micrófono Dinámico Cardioide",
        "marca": "Shure",
        "modelo": "SM58",
        "categoria": "Micrófonos",
        "precio": 149990,
        "stock": 8,
        "descripcion": "Estándar industria para voz en vivo.",
        "imagen": "https://placehold.co/600x400?text=Micrófonos"
    },
    {
        "id": 28,
        "codigo": "MI002",
        "nombre": "Micrófono Dinámico Instrumento",
        "marca": "Shure",
        "modelo": "SM57",
        "categoria": "Micrófonos",
        "precio": 139990,
        "stock": 6,
        "descripcion": "Ideal para captura de instrumentos y amplificadores.",
        "imagen": "https://placehold.co/600x400?text=Micrófonos"
    },
    {
        "id": 29,
        "codigo": "MI003",
        "nombre": "Micrófono Condensador",
        "marca": "Audio-Tech.",
        "modelo": "AT2020",
        "categoria": "Micrófonos",
        "precio": 199990,
        "stock": 4,
        "descripcion": "Cardioide, XLR, ideal para grabación en estudio.",
        "imagen": "https://placehold.co/600x400?text=Micrófonos"
    },
    {
        "id": 30,
        "codigo": "MI004",
        "nombre": "Micrófono USB de Condensador",
        "marca": "Blue",
        "modelo": "Yeti",
        "categoria": "Micrófonos",
        "precio": 299990,
        "stock": 5,
        "descripcion": "USB, 4 patrones polares, ideal para streaming y podcast.",
        "imagen": "https://placehold.co/600x400?text=Micrófonos"
    },
    {
        "id": 31,
        "codigo": "PE001",
        "nombre": "Pedal Distorsión",
        "marca": "Boss",
        "modelo": "DS-1",
        "categoria": "Pedales de Efectos",
        "precio": 79990,
        "stock": 7,
        "descripcion": "Clásico pedal de distorsión, 3 controles.",
        "imagen": "https://placehold.co/600x400?text=Pedales+de+Efectos"
    },
    {
        "id": 32,
        "codigo": "PE002",
        "nombre": "Pedal Reverb",
        "marca": "Boss",
        "modelo": "RV-6",
        "categoria": "Pedales de Efectos",
        "precio": 179990,
        "stock": 4,
        "descripcion": "8 modos de reverb, control de shimmer.",
        "imagen": "https://placehold.co/600x400?text=Pedales+de+Efectos"
    },
    {
        "id": 33,
        "codigo": "PE003",
        "nombre": "Pedal Multi-efectos",
        "marca": "Boss",
        "modelo": "ME-80",
        "categoria": "Pedales de Efectos",
        "precio": 349990,
        "stock": 2,
        "descripcion": "Diseño tipo pedalboard, 8 efectos simultáneos.",
        "imagen": "https://placehold.co/600x400?text=Pedales+de+Efectos"
    },
    {
        "id": 34,
        "codigo": "PE004",
        "nombre": "Pedal Tuner Cromático",
        "marca": "Boss",
        "modelo": "TU-3",
        "categoria": "Pedales de Efectos",
        "precio": 89990,
        "stock": 8,
        "descripcion": "Afinador cromático, indicador de tono.",
        "imagen": "https://placehold.co/600x400?text=Pedales+de+Efectos"
    },
    {
        "id": 35,
        "codigo": "PE005",
        "nombre": "Pedal Delay",
        "marca": "MXR",
        "modelo": "Carbon Copy",
        "categoria": "Pedales de Efectos",
        "precio": 179990,
        "stock": 4,
        "descripcion": "Delay analógico cálido, tiempo 600ms.",
        "imagen": "https://placehold.co/600x400?text=Pedales+de+Efectos"
    },
    {
        "id": 36,
        "codigo": "PE006",
        "nombre": "Pedal Overdrive",
        "marca": "Ibanez",
        "modelo": "TS9",
        "categoria": "Pedales de Efectos",
        "precio": 99990,
        "stock": 6,
        "descripcion": "Tube Screamer clásico, sonido suave y orgánico.",
        "imagen": "https://placehold.co/600x400?text=Pedales+de+Efectos"
    },
    {
        "id": 37,
        "codigo": "AC001",
        "nombre": "Cuerdas Guitarra Eléctrica 09-42",
        "marca": "Ernie Ball",
        "modelo": "Super Slinky",
        "categoria": "Accesorios",
        "precio": 8990,
        "stock": 25,
        "descripcion": "Juego 6 cuerdas, calibre ligero.",
        "imagen": "https://placehold.co/600x400?text=Accesorios"
    },
    {
        "id": 38,
        "codigo": "AC002",
        "nombre": "Cuerdas Guitarra Acústica 12-53",
        "marca": "Ernie Ball",
        "modelo": "Earthwood",
        "categoria": "Accesorios",
        "precio": 10990,
        "stock": 20,
        "descripcion": "Bronce fósforo, sonido cálido.",
        "imagen": "https://placehold.co/600x400?text=Accesorios"
    },
    {
        "id": 39,
        "codigo": "AC003",
        "nombre": "Cuerdas Bajo 45-105",
        "marca": "Ernie Ball",
        "modelo": "Regular Slinky",
        "categoria": "Accesorios",
        "precio": 14990,
        "stock": 12,
        "descripcion": "Cuerdas de níquel enrollado, set 4 cuerdas.",
        "imagen": "https://placehold.co/600x400?text=Accesorios"
    },
    {
        "id": 40,
        "codigo": "AC004",
        "nombre": "Púas de Guitarra x10 (0.73mm)",
        "marca": "Fender",
        "modelo": "351",
        "categoria": "Accesorios",
        "precio": 3990,
        "stock": 50,
        "descripcion": "Celulosa, grosor medio.",
        "imagen": "https://placehold.co/600x400?text=Accesorios"
    },
    {
        "id": 41,
        "codigo": "AC005",
        "nombre": "Capotraste Guitarra",
        "marca": "Dunlop",
        "modelo": "Trigger",
        "categoria": "Accesorios",
        "precio": 12990,
        "stock": 15,
        "descripcion": "Capotraste de resorte, compatible 6 cuerdas.",
        "imagen": "https://placehold.co/600x400?text=Accesorios"
    },
    {
        "id": 42,
        "codigo": "AC006",
        "nombre": "Afinador de Clip",
        "marca": "Snark",
        "modelo": "SN-5",
        "categoria": "Accesorios",
        "precio": 8990,
        "stock": 20,
        "descripcion": "Afinador cromático de clip, pantalla giratoria.",
        "imagen": "https://placehold.co/600x400?text=Accesorios"
    },
    {
        "id": 43,
        "codigo": "AC007",
        "nombre": "Cable Instrumento 3m",
        "marca": "Monster",
        "modelo": "S100-I-3",
        "categoria": "Accesorios",
        "precio": 12990,
        "stock": 15,
        "descripcion": "Cable trenzado, conectores dorados, 3 metros.",
        "imagen": "https://placehold.co/600x400?text=Accesorios"
    },
    {
        "id": 44,
        "codigo": "AC008",
        "nombre": "Cable Instrumento 6m",
        "marca": "Monster",
        "modelo": "S100-I-6",
        "categoria": "Accesorios",
        "precio": 17990,
        "stock": 10,
        "descripcion": "Cable trenzado, conectores dorados, 6 metros.",
        "imagen": "https://placehold.co/600x400?text=Accesorios"
    },
    {
        "id": 45,
        "codigo": "AC009",
        "nombre": "Soporte Guitarra de Piso",
        "marca": "Hercules",
        "modelo": "GS302B",
        "categoria": "Accesorios",
        "precio": 22990,
        "stock": 12,
        "descripcion": "Soporte plegable con enganche automático.",
        "imagen": "https://placehold.co/600x400?text=Accesorios"
    },
    {
        "id": 46,
        "codigo": "AC010",
        "nombre": "Soporte Guitarra de Pared",
        "marca": "Hercules",
        "modelo": "WAH-202",
        "categoria": "Accesorios",
        "precio": 18990,
        "stock": 10,
        "descripcion": "Montaje a pared, enganche automático.",
        "imagen": "https://placehold.co/600x400?text=Accesorios"
    },
    {
        "id": 47,
        "codigo": "ES001",
        "nombre": "Interfaz de Audio 2x2 USB",
        "marca": "Focusrite",
        "modelo": "Scarlett Solo",
        "categoria": "Estudio y Grabación",
        "precio": 149990,
        "stock": 4,
        "descripcion": "1 entrada XLR+instrumento, 2 salidas, 24bit/192kHz.",
        "imagen": "https://placehold.co/600x400?text=Estudio+y+Grabación"
    },
    {
        "id": 48,
        "codigo": "ES002",
        "nombre": "Auriculares de Estudio",
        "marca": "Audio-Tech.",
        "modelo": "ATH-M20x",
        "categoria": "Estudio y Grabación",
        "precio": 79990,
        "stock": 6,
        "descripcion": "Circumaurales, respuesta 15Hz-20kHz.",
        "imagen": "https://placehold.co/600x400?text=Estudio+y+Grabación"
    },
    {
        "id": 49,
        "codigo": "ES003",
        "nombre": "Auriculares de Estudio Pro",
        "marca": "Audio-Tech.",
        "modelo": "ATH-M50x",
        "categoria": "Estudio y Grabación",
        "precio": 219990,
        "stock": 4,
        "descripcion": "Referencia de industria, sonido neutro y detallado.",
        "imagen": "https://placehold.co/600x400?text=Estudio+y+Grabación"
    },
    {
        "id": 50,
        "codigo": "ES004",
        "nombre": "Monitor de Estudio 5\"",
        "marca": "Yamaha",
        "modelo": "HS5",
        "categoria": "Estudio y Grabación",
        "precio": 349990,
        "stock": 2,
        "descripcion": "Altavoz activo, respuesta plana, ideal mezcla.",
        "imagen": "https://placehold.co/600x400?text=Estudio+y+Grabación"
    },
    {
        "id": 51,
        "codigo": "ES005",
        "nombre": "Pop Filter para Micrófono",
        "marca": "Sennheiser",
        "modelo": "MZP 40",
        "categoria": "Estudio y Grabación",
        "precio": 14990,
        "stock": 8,
        "descripcion": "Doble malla, brazo flexible con clip.",
        "imagen": "https://placehold.co/600x400?text=Estudio+y+Grabación"
    }
];




